-- Схема базы данных перелётов
CREATE SCHEMA IF NOT EXISTS flight_repository;

-- ────────────────────────────────────────────────────────────
-- airport (аэропорт)
--   code — уникальный код (PK, например: SVO, LED, JFK)
-- ────────────────────────────────────────────────────────────
CREATE TABLE flight_repository.airport (
    code    VARCHAR(3)  PRIMARY KEY,            -- IATA-код: строго 3 символа
    country VARCHAR(50) NOT NULL,
    city    VARCHAR(50) NOT NULL
);

-- ────────────────────────────────────────────────────────────
-- aircraft (самолёт)
-- ────────────────────────────────────────────────────────────
CREATE TABLE flight_repository.aircraft (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model VARCHAR(50) NOT NULL UNIQUE
);

-- ────────────────────────────────────────────────────────────
-- seat (место в самолёте)
--   PK — составной (aircraft_id + seat_no),
--   потому что номера мест уникальны в пределах самолёта
-- ────────────────────────────────────────────────────────────
CREATE TABLE flight_repository.seat (
    aircraft_id BIGINT      NOT NULL REFERENCES flight_repository.aircraft (id),
    seat_no     VARCHAR(4)  NOT NULL,           -- например: 12A, 1B
    PRIMARY KEY (aircraft_id, seat_no)
);

-- ────────────────────────────────────────────────────────────
-- flight (рейс)
--   flight_no — НЕ уникален (один номер рейса летает каждый день)
--   status    — строго одно из четырёх значений
-- ────────────────────────────────────────────────────────────
CREATE TYPE flight_repository.flight_status
    AS ENUM ('SCHEDULED', 'DEPARTED', 'ARRIVED', 'CANCELLED');

CREATE TABLE flight_repository.flight (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_no              VARCHAR(10)                          NOT NULL,
    departure_date         TIMESTAMP                            NOT NULL,
    departure_airport_code VARCHAR(3)                           NOT NULL
        REFERENCES flight_repository.airport (code),
    arrival_date           TIMESTAMP                            NOT NULL,
    arrival_airport_code   VARCHAR(3)                           NOT NULL
        REFERENCES flight_repository.airport (code),
    aircraft_id            BIGINT                               NOT NULL
        REFERENCES flight_repository.aircraft (id),
    status                 flight_repository.flight_status      NOT NULL
        DEFAULT 'SCHEDULED'
);

CREATE INDEX idx_flight_no     ON flight_repository.flight (flight_no);
CREATE INDEX idx_flight_depart ON flight_repository.flight (departure_date);

-- ────────────────────────────────────────────────────────────
-- ticket (билет)
--   (flight_id + seat_no) — уникальны: одно место на одном рейсе
--   можно продать только один раз
-- ────────────────────────────────────────────────────────────
CREATE TABLE flight_repository.ticket (
    id             BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_no   VARCHAR(20)     NOT NULL,                    -- номер паспорта
    passenger_name VARCHAR(100)    NOT NULL,                    -- имя и фамилия
    flight_id      BIGINT          NOT NULL
        REFERENCES flight_repository.flight (id),
    seat_no        VARCHAR(4)      NOT NULL,
    cost           NUMERIC(10, 2)  NOT NULL CHECK (cost >= 0),
    CONSTRAINT uq_ticket_seat UNIQUE (flight_id, seat_no)
);

CREATE INDEX idx_ticket_passenger ON flight_repository.ticket (passenger_no);
CREATE INDEX idx_ticket_flight    ON flight_repository.ticket (flight_id);

