# Spring Boot JPA batch configuration

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5450/learn
spring.datasource.username=learn
spring.datasource.password=learn
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Batch settings
spring.jpa.properties.hibernate.jdbc.batch_size=5
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.default_batch_fetch_size=5
# Logging to see batch execution
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.stat=DEBUG

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
server.port=8081

# StatementInspector для подсчёта вызовов nextval в демо
spring.jpa.properties.hibernate.session_factory.statement_inspector=com.example.hibernatelearn.SequenceCallCounter
